Repository Telmate/proxmox-api-go, pull requests merged in 2024-11, with the labels that each got.

#371 Rework: qemu usb
  .gitignore
  proxmox/config_qemu.go
  proxmox/config_qemu_cloudinit.go
  proxmox/config_qemu_test.go
  proxmox/config_qemu_usb.go
  proxmox/config_qemu_usb_test.go
  proxmox/resource_mapping.go
  proxmox/resource_mapping_test.go
  test/data/test_data_resourcemapping/type_ResourceMappingUsbID.go
Labels: enhancement

#374 Optimize
  docs/style-guide/sdk.md
  proxmox/config_group.go
  proxmox/config_group_test.go
  proxmox/config_qemu.go
  proxmox/config_qemu_test.go
  proxmox/config_qemu_usb.go
  proxmox/config_user.go
  proxmox/session.go
Labels: refactor

#375 fix: `QemuUSBs` iterating non existing items
  proxmox/config_qemu_usb.go
Labels: bug

#376 feat: Full Qemu PCI support
  proxmox/config_qemu.go
  proxmox/config_qemu_pcie.go
  proxmox/config_qemu_pcie_test.go
  proxmox/config_qemu_test.go
  proxmox/resource_mapping.go
  proxmox/util.go
  proxmox/util_test.go
Labels: enhancement

#373 feat: client intialized with ticket and CSRF prevention Token
  proxmox/client.go
  proxmox/session.go
Labels: enhancement

#385 feat: use same mac address case
  proxmox/config_qemu_network.go
  proxmox/config_qemu_test.go
Labels: type/enhancement, type/refactoring, size/M, test/done
