Repository Telmate/proxmox-api-go, pull requests merged in 2025-05, with the labels that each got.

#414 Fix: cpu flags set when no flags should be set
  proxmox/config_qemu_cpu.go
  proxmox/config_qemu_test.go
Labels: type/bug, modifies/go, size/M

#416 fix: `vmId` not set in `VmRef`
  proxmox/config_qemu.go
Labels: type/bug, modifies/go, size/XS, test/done

#412 feature/import-from: add import-from feature to disks on create
  proxmox/config_qemu_disk.go
  proxmox/config_qemu_disk_ide.go
  proxmox/config_qemu_disk_sata.go
  proxmox/config_qemu_disk_scsi.go
  proxmox/config_qemu_disk_virtio.go
Labels: type/feature, modifies/go, size/S, test/needen

#418 feat: explicit disk deletion
  proxmox/config_qemu_disk.go
  proxmox/config_qemu_disk_ide.go
  proxmox/config_qemu_disk_sata.go
  proxmox/config_qemu_disk_scsi.go
  proxmox/config_qemu_disk_virtio.go
  proxmox/config_qemu_test.go
Labels: type/enhancement, modifies/go, size/L, test/done
