Repository Telmate/proxmox-api-go, pull requests merged in 2025-01, with the labels that each got.

#393 redefine `nocheck` and `_unsafe`
  docs/style-guide/sdk.md
  proxmox/config_guest.go
  proxmox/config_pool.go
  proxmox/config_pool_test.go
  proxmox/config_qemu.go
  proxmox/snapshot.go
Labels: type/enhancement, modifies/docs, modifies/go, size/L

#395 fix: usb port parsing
  proxmox/config_qemu_usb.go
  proxmox/config_qemu_usb_test.go
Labels: type/enhancement, modifies/go, size/S

#398 feat: ssh `AuthorizedKey` type
  go.mod
  go.sum
  proxmox/config_qemu_cloudinit.go
  proxmox/config_qemu_cloudinit_test.go
  proxmox/config_qemu_test.go
  proxmox/type_authorizedkey.go
  proxmox/type_authorizedkey_test.go
  proxmox/util.go
  test/data/test_data_qemu/type_PublicKey.go
Labels: type/enhancement, modifies/go, size/XL, modifies/dependencies
